_target_: src.tuners.cb_tuner.CBTuner
hparams:
  objective: RMSE
  loss_function: RMSE
  iterations:
    low: 8
    high: 1024
    step: 1
  learning_rate:
    low: 0.0001
    high: 1.0
    log: True
  depth:
    low: 1
    high: 10
  l2_leaf_reg:
    low: 1
    high: 10
    log: True
  model_size_reg:
    low: 0.1
    high: 10.0
    log: True
  rsm:
    low: 0.1
    high: 1.0
  subsample:
    low: 0.1
    high: 1.0
  border_count:
    low: 32
    high: 255
  feature_border_type:
    - Median
    - Uniform
    - UniformAndQuantiles
    - MaxLogSum
    - MinEntropy
    - GreedyLogSum
  bootstrap_type:
    - Bayesian
    - Bernoulli
    - MVS
  grow_policy:
    - SymmetricTree
    - Lossguide
    - Depthwise
  leaf_estimation_method:
    - Newton
    - Gradient
  random_strength:
    low: 1
    high: 100
  bagging_temperature:
    low: 0.1
    high: 1.0
split_size: ${split_size}
num_folds: ${num_folds}
num_trials: ${num_trials}
seed: ${seed}
tuning_way: ${tuning_way}
hparams_save_path: ${hparams_save_path}