_target_: src.tuners.cb_tuner.CBTuner
hparams:
  objective: RMSE
  loss_function: RMSE
  boosting_type: 
    - Ordered
    - Plain
  learning_rate:
    low: 0.0001
    high: 0.1
    log: True
  n_estimators:
    low: 8
    high: 1024
    step: 1
    log: True
  min_child_samples:
    low: 1
    high: 100
    log: False
  subsample:
    low: 0.1
    high: 1.0
split_size: ${split_size}
num_folds: ${num_folds}
num_trials: ${num_trials}
seed: ${seed}
tuning_way: ${tuning_way}
hparams_save_path: ${hparams_save_path}