# @package _global_
defaults:
  - dataset: house_price_dataset
  - architecture: cb_architecture
  - tuner: cb_tuner
  - hydra: hydra

project_dir: ${oc.env:PROJECT_DIR}
connected_dir: ${oc.env:CONNECTED_DIR}

seed: 2024

model_name: CatBoost
dataset_name: HousePrice
mode: train
label_column_name: target
scale: unscale
num_folds: 5

is_tuned: untuned
split_size: 0.2
num_trials: 100
tuning_way: original
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${tuning_way}/${num_trials}_trials

project_name: ${model_name}-${dataset_name}-${mode}
model_save_path: ${connected_dir}/save_model/${model_name}/${dataset_name}/${is_tuned}
result_summary_path: ${connected_dir}/result_summary/${model_name}/${dataset_name}/${is_tuned}
plt_save_path: ${connected_dir}/feature_importance/${model_name}/${dataset_name}/${is_tuned}
submission_save_path: ${connected_dir}/submission
submission_save_name: ${model_name}-${dataset_name}-${num_folds}-${is_tuned}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}